service-values:
  em-srv:
    type: enterprise-messaging
    instance: 08e05475-9811-4a2b-9cc9-0406686227de
    key: emkey
  destination-srv:
    type: destination
    instance: fb393794-e5a9-4b9d-8d94-24d011514057
    key: destkey
secret-values:
  destination-name:
    name:
      name: RegisteredoData
      attachmentSrvApi: API_CV_ATTACHMENT_SRV
      businessPartnerSrvApi:  API_BUSINESS_PARTNER
      businessObjectTypeName: BUS1006
config-values:
  amqp-service-config:
    amqp:
      incoming:
        inp1:
          sourceAddress: queue:refapps/bpems/abc/MyQueue
          sndSettleMode: 0
          rcvSettleMode: 0
          maxLinkCredit: 50
    bind:
      rules:
        - filter:
            incoming: inp1
          action:
            function: qrcodegenerator
            failure: accept
            content: application/json
